### ISSUE TITLE
Using VIM, but comments still misaligned

### ISSUE THREAD

**Issue by ghost** [geekcomputers/Shell#2]
Is there something I need to set in vim for it to show correctly? They are a complete mess and I don't want to request a pull if it means messing up your alignment setup thing.

When you say vi in README.md, do you mean *actual* vi? lol Sorry if that's a stupid question.

EDIT: Sorry for reopening -- still trying to familiarize myself with GitHub.

**Comment by geekcomputers** [comment]
What's the issue here lets see if I can help

**Comment by ghost** [comment]
It's okay. The comments were just very misaligned when in VIM. Feel free to delete this issue, if that's possible. Sorry for the inconvenience , and you're welcome for the contribution. :)
